<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;

class SeafoodCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $storageDir = storage_path('app/public/products');
        if (!file_exists($storageDir)) {
            mkdir($storageDir, 0755, true);
        }

        // Fetch / Ensure all 18 Categories exist
        $fishCat        = Category::firstOrCreate(['slug' => 'fish'], ['name' => 'Fish', 'sort_order' => 1, 'is_active' => true, 'is_featured' => true]);
        $prawnCat       = Category::firstOrCreate(['slug' => 'prawns-shrimps'], ['name' => 'Prawns / Shrimps', 'sort_order' => 2, 'is_active' => true, 'is_featured' => true]);
        $squidCat       = Category::firstOrCreate(['slug' => 'squid'], ['name' => 'Squid', 'sort_order' => 3, 'is_active' => true, 'is_featured' => true]);
        $crabCat        = Category::firstOrCreate(['slug' => 'crab'], ['name' => 'Crab', 'sort_order' => 4, 'is_active' => true, 'is_featured' => true]);
        $shellCat       = Category::firstOrCreate(['slug' => 'shellfish'], ['name' => 'Shellfish', 'sort_order' => 5, 'is_active' => true, 'is_featured' => true]);
        $prodCat        = Category::firstOrCreate(['slug' => 'seafood-products'], ['name' => 'Seafood Products', 'sort_order' => 6, 'is_active' => true, 'is_featured' => true]);
        $filletCat      = Category::firstOrCreate(['slug' => 'fish-fillet'], ['name' => 'Fish Fillet', 'sort_order' => 7, 'is_active' => true, 'is_featured' => true]);
        $otherSeaCat    = Category::firstOrCreate(['slug' => 'other-frozen-seafood'], ['name' => 'Other Frozen Seafood', 'sort_order' => 8, 'is_active' => true, 'is_featured' => false]);
        $steamboatCat   = Category::firstOrCreate(['slug' => 'steamboat'], ['name' => 'Steamboat', 'sort_order' => 9, 'is_active' => true, 'is_featured' => true]);
        $meatChickenCat = Category::firstOrCreate(['slug' => 'meat-chicken'], ['name' => 'Meat Chicken', 'sort_order' => 10, 'is_active' => true, 'is_featured' => false]);
        $meatLambCat    = Category::firstOrCreate(['slug' => 'meat-lamb'], ['name' => 'Meat Lamb', 'sort_order' => 11, 'is_active' => true, 'is_featured' => false]);
        $meatBeefCat    = Category::firstOrCreate(['slug' => 'meat-beef'], ['name' => 'Meat Beef', 'sort_order' => 12, 'is_active' => true, 'is_featured' => true]);
        $meatDuckCat    = Category::firstOrCreate(['slug' => 'meat-duck'], ['name' => 'Meat Duck', 'sort_order' => 13, 'is_active' => true, 'is_featured' => false]);
        $frozenFoodCat  = Category::firstOrCreate(['slug' => 'frozen-product-food'], ['name' => 'Frozen Product Food', 'sort_order' => 14, 'is_active' => true, 'is_featured' => false]);
        $dimsumCat      = Category::firstOrCreate(['slug' => 'dimsum'], ['name' => 'Dimsum', 'sort_order' => 15, 'is_active' => true, 'is_featured' => true]);
        $readyEatCat    = Category::firstOrCreate(['slug' => 'ready-to-eat'], ['name' => 'Ready to Eat', 'sort_order' => 16, 'is_active' => true, 'is_featured' => false]);
        $snackCat       = Category::firstOrCreate(['slug' => 'snack-food'], ['name' => 'Snack Food', 'sort_order' => 17, 'is_active' => true, 'is_featured' => false]);
        $dessertCat     = Category::firstOrCreate(['slug' => 'dessert'], ['name' => 'Dessert', 'sort_order' => 18, 'is_active' => true, 'is_featured' => false]);

        $products = [
            // ─── 1. FISH ─────────────────────────────────────────────────────────────
            [
                'name'                => 'Atlantic Salmon Fillet (500g)',
                'slug'                => 'atlantic-salmon-fillet-500g',
                'category_id'         => $fishCat->id,
                'short_description'   => 'Premium sashimi-grade Norwegian Atlantic salmon fillet, skin-on and pin-bone out.',
                'description'         => 'Sourced directly from cold Norwegian fjords, our Atlantic salmon fillets feature rich omega-3 fatty acids, vibrant marbling, and tender texture. Flash-frozen with Individual Quick Freezing (IQF) technology to preserve oceanic freshness. Ideal for pan-searing, baking with herb butter, or air-frying.',
                'sku'                 => 'FISH-SAL-500',
                'retail_price'        => 28.90,
                'walkin_price'        => 25.90,
                'wholesale_price'     => 22.00,
                'trading_price'       => 19.50,
                'weight'              => '500g',
                'unit'                => 'pack',
                'origin'              => 'Norway',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 250,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 50,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 1,
                'thumbnail'           => 'products/salmon_fillet_premium.jpg',
            ],
            [
                'name'                => 'Barramundi / Siakap Whole Cleaned (750g)',
                'slug'                => 'barramundi-siakap-whole-750g',
                'category_id'         => $fishCat->id,
                'short_description'   => 'Farm-fresh Asian Seabass (Siakap), de-scaled, gutted and vacuum sealed.',
                'description'         => 'Premium live-harvested Barramundi (Ikan Siakap) processed immediately under strict HACCP hygiene standards. Sweet, delicate white flakes with clean ocean flavor. Ready-to-cook for classic Malaysian Teochew steamed fish, Thai sweet and sour, or oven-roasted.',
                'sku'                 => 'FISH-SIAKAP-750',
                'retail_price'        => 24.50,
                'walkin_price'        => 22.00,
                'wholesale_price'     => 18.50,
                'trading_price'       => 16.00,
                'weight'              => '750g',
                'unit'                => 'fish',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 140,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 15,
                'moq_trading'         => 60,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 2,
                'thumbnail'           => 'products/barramundi_seabass.jpg',
            ],
            [
                'name'                => 'Red Snapper / Ikan Merah Fillet (500g)',
                'slug'                => 'red-snapper-ikan-merah-fillet-500g',
                'category_id'         => $fishCat->id,
                'short_description'   => 'Wild-caught Red Snapper fillets, skin-on with sweet firm white meat.',
                'description'         => 'Prized for its firm, lean meat and subtly sweet, nutty profile, our wild-caught Red Snapper is carefully portioned into 500g packs. Ideal for traditional Malaysian fish head curry, grilling over banana leaf, or fine dining pan-roasting.',
                'sku'                 => 'FISH-SNAP-500',
                'retail_price'        => 29.90,
                'walkin_price'        => 27.00,
                'wholesale_price'     => 23.50,
                'trading_price'       => 21.00,
                'weight'              => '500g',
                'unit'                => 'pack',
                'origin'              => 'Indonesia',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 165,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 50,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 3,
                'thumbnail'           => 'products/red_snapper_fillet.jpg',
            ],
            [
                'name'                => 'Spanish Mackerel / Tenggiri Steak (500g)',
                'slug'                => 'spanish-mackerel-tenggiri-steak-500g',
                'category_id'         => $fishCat->id,
                'short_description'   => 'Center-cut wild Tenggiri fish steaks, rich in flavor and nutrient-dense.',
                'description'         => 'Prime center-cut slices of wild Spanish Mackerel (Ikan Tenggiri Batang). Dense, meaty texture with natural oceanic umami. Perfect for classic Malaysian Tenggiri Goreng Kunyit, Assam Pedas, or homemade fish paste.',
                'sku'                 => 'FISH-TENG-500',
                'retail_price'        => 26.00,
                'walkin_price'        => 23.50,
                'wholesale_price'     => 20.00,
                'trading_price'       => 18.00,
                'weight'              => '500g',
                'unit'                => 'pack',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 120,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 50,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 4,
                'thumbnail'           => 'products/tenggiri_steak.jpg',
            ],

            // ─── 2. PRAWNS / SHRIMPS ──────────────────────────────────────────────
            [
                'name'                => 'Jumbo Black Tiger Prawns (1kg)',
                'slug'                => 'jumbo-black-tiger-prawns-1kg',
                'category_id'         => $prawnCat->id,
                'short_description'   => 'Grade-A wild caught black tiger prawns with firm, juicy sweet meat.',
                'description'         => 'Wild sea-caught Black Tiger Prawns from the coastal waters of Sabah. Uncompromised snap and natural sweetness. Approx. 16-20 pieces per kg. Exceptional choice for BBQ charcoal grilling, butter garlic stir-fry, and wedding banquets.',
                'sku'                 => 'CRUST-TPRAWN-1KG',
                'retail_price'        => 48.90,
                'walkin_price'        => 45.00,
                'wholesale_price'     => 39.00,
                'trading_price'       => 35.00,
                'weight'              => '1kg',
                'unit'                => 'box',
                'origin'              => 'Sabah, Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 175,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 5,
                'moq_trading'         => 20,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 5,
                'thumbnail'           => 'products/black_tiger_prawns.jpg',
            ],
            [
                'name'                => 'Sea White Prawns / Udang Kertas (1kg)',
                'slug'                => 'sea-white-prawns-udang-kertas-1kg',
                'category_id'         => $prawnCat->id,
                'short_description'   => 'Translucent thin-shelled sea white prawns, naturally sweet and tender.',
                'description'         => 'Wild-caught Sea White Prawns (Udang Kertas/Laut) featuring paper-thin shells and intensely sweet, bouncy meat. Count: 31-40 pcs/kg. The definitive standard for Chinese herbal steaming, sambal udang, and hotpot broth.',
                'sku'                 => 'CRUST-WPRAWN-1KG',
                'retail_price'        => 38.00,
                'walkin_price'        => 35.00,
                'wholesale_price'     => 30.00,
                'trading_price'       => 27.50,
                'weight'              => '1kg',
                'unit'                => 'box',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 210,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 40,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 6,
                'thumbnail'           => 'products/sea_white_prawns.jpg',
            ],
            [
                'name'                => 'Peeled & Deveined King Prawns (500g)',
                'slug'                => 'peeled-deveined-king-prawns-500g',
                'category_id'         => $prawnCat->id,
                'short_description'   => '100% net weight peeled, tail-on king prawn cutlets, ready to cook.',
                'description'         => 'Convenient restaurant-grade peeled, deveined prawn cutlets with tails left intact for presentation. No glaze weight deception — pure net weight. Perfect for shrimp scampi, fried rice, and tempura.',
                'sku'                 => 'CRUST-PEELED-500',
                'retail_price'        => 27.50,
                'walkin_price'        => 25.00,
                'wholesale_price'     => 21.00,
                'trading_price'       => 18.50,
                'weight'              => '500g',
                'unit'                => 'pack',
                'origin'              => 'Vietnam',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 300,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 50,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 7,
                'thumbnail'           => 'products/peeled_king_prawns.jpg',
            ],

            // ─── 3. SQUID ─────────────────────────────────────────────────────────
            [
                'name'                => 'Fresh Loligo Squid / Sotong Jarum (1kg)',
                'slug'                => 'fresh-loligo-squid-sotong-jarum-1kg',
                'category_id'         => $squidCat->id,
                'short_description'   => 'Ocean-fresh whole needle squid with glossy translucent tubes and tentacles.',
                'description'         => 'Whole Loligo Squid (Sotong Jarum) frozen right after ocean trawling to prevent rubberiness. Tender when flash-cooked, releasing sweet natural juice. Superb for sotong bakar, sambal petai sotong, or stuffed squid.',
                'sku'                 => 'CEPH-LOLIGO-1KG',
                'retail_price'        => 32.00,
                'walkin_price'        => 29.50,
                'wholesale_price'     => 25.00,
                'trading_price'       => 22.00,
                'weight'              => '1kg',
                'unit'                => 'kg',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 220,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 50,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 8,
                'thumbnail'           => 'products/loligo_squid.jpg',
            ],
            [
                'name'                => 'Crispy Calamari Squid Rings (500g IQF)',
                'slug'                => 'crispy-calamari-squid-rings-500g',
                'category_id'         => $squidCat->id,
                'short_description'   => 'Evenly cut tender calamari rings, Individual Quick Frozen for easy portioning.',
                'description'         => 'Pre-cleaned and tenderized squid rings cut to standard thickness. Zero preparation hassle — cook straight from semi-thawed state. High crisp retention when deep fried for salt & pepper calamari rings.',
                'sku'                 => 'CEPH-RINGS-500',
                'retail_price'        => 15.90,
                'walkin_price'        => 14.00,
                'wholesale_price'     => 11.50,
                'trading_price'       => 9.80,
                'weight'              => '500g',
                'unit'                => 'pack',
                'origin'              => 'Thailand',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 400,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 20,
                'moq_trading'         => 100,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 9,
                'thumbnail'           => 'products/squid_rings_iqf.jpg',
            ],

            // ─── 4. CRAB ──────────────────────────────────────────────────────────
            [
                'name'                => 'Live Mud Crabs / Ketam Nipah (~800g Pair)',
                'slug'                => 'live-mud-crabs-ketam-nipah-800g',
                'category_id'         => $crabCat->id,
                'short_description'   => 'Live Grade-A male mud crabs with massive claws and succulent sweet flesh.',
                'description'         => 'Wild mangrove mud crabs (Ketam Nipah) sourced from clean estuaries. Solid meat yield (>85%) with rich oceanic sweetness and firm claw meat. The gold standard for Singapore Chilli Crab, Black Pepper Crab, and Salted Egg Yolk Crab.',
                'sku'                 => 'CRAB-MUD-800',
                'retail_price'        => 58.00,
                'walkin_price'        => 54.00,
                'wholesale_price'     => 46.00,
                'trading_price'       => 42.00,
                'weight'              => '800g',
                'unit'                => 'pair',
                'origin'              => 'Indonesia',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 80,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 5,
                'moq_trading'         => 25,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 10,
                'thumbnail'           => 'products/mud_crabs_live.jpg',
            ],
            [
                'name'                => 'Blue Swimmer Flower Crab (500g)',
                'slug'                => 'blue-swimmer-flower-crab-500g',
                'category_id'         => $crabCat->id,
                'short_description'   => 'Wild-harvested blue flower crabs, flash frozen to preserve delicate sweetness.',
                'description'         => 'Wild blue swimming flower crabs renowned for their light, naturally sugary meat and tender texture. 3-4 crabs per 500g tray. Ideal for seafood curries, noodle broths, or simple Chinese steaming with egg white and Shaoxing wine.',
                'sku'                 => 'CRAB-FLOWER-500',
                'retail_price'        => 22.50,
                'walkin_price'        => 20.00,
                'wholesale_price'     => 16.50,
                'trading_price'       => 14.00,
                'weight'              => '500g',
                'unit'                => 'pack',
                'origin'              => 'Indonesia',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 190,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 50,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 11,
                'thumbnail'           => 'products/flower_crab_fresh.jpg',
            ],
            [
                'name'                => 'Crispy Soft Shell Crab (1kg)',
                'slug'                => 'crispy-soft-shell-crab-1kg',
                'category_id'         => $crabCat->id,
                'short_description'   => 'Premium frozen soft shell crabs, 100% edible whole crab without peeling.',
                'description'         => 'Harvested immediately following molting when the shell is soft and paper-thin. Whole crab is 100% edible. 8-10 pieces per 1kg box. A restaurant favorite for Japanese maki hand rolls, soft shell crab burgers, and golden salted egg dishes.',
                'sku'                 => 'CRAB-SOFT-1KG',
                'retail_price'        => 65.00,
                'walkin_price'        => 60.00,
                'wholesale_price'     => 52.00,
                'trading_price'       => 48.00,
                'weight'              => '1kg',
                'unit'                => 'box',
                'origin'              => 'Myanmar',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 110,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 5,
                'moq_trading'         => 20,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 12,
                'thumbnail'           => 'products/soft_shell_crab.jpg',
            ],

            // ─── 5. SHELLFISH ─────────────────────────────────────────────────────
            [
                'name'                => 'Canadian Sea Scallops (500g Sashimi Grade)',
                'slug'                => 'canadian-sea-scallops-500g',
                'category_id'         => $shellCat->id,
                'short_description'   => 'Wild-caught colossal Canadian sea scallops, dry-packed with no added water.',
                'description'         => 'Premium natural dry-pack sea scallops wild-harvested in the icy waters of the North Atlantic. Plump, buttery texture with deep caramelization when seared. Certified chemical-free and unsoaked.',
                'sku'                 => 'SHELL-SCALLOP-500',
                'retail_price'        => 49.00,
                'walkin_price'        => 45.00,
                'wholesale_price'     => 38.00,
                'trading_price'       => 34.00,
                'weight'              => '500g',
                'unit'                => 'pack',
                'origin'              => 'Canada',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 150,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 8,
                'moq_trading'         => 30,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 13,
                'thumbnail'           => 'products/canadian_scallops.jpg',
            ],
            [
                'name'                => 'Half-Shell Green Mussels (1kg)',
                'slug'                => 'half-shell-green-mussels-1kg',
                'category_id'         => $shellCat->id,
                'short_description'   => 'Plump New Zealand Greenshell mussels on half shell, pre-cleaned.',
                'description'         => 'Native to New Zealand, these distinct green-edged mussels are cultivated in clear oceanic bays. Sweet, robust flavor and dense plump meat. Perfect for garlic cheese baking, white wine steaming, or seafood paella.',
                'sku'                 => 'SHELL-MUSSEL-1KG',
                'retail_price'        => 24.00,
                'walkin_price'        => 21.50,
                'wholesale_price'     => 17.50,
                'trading_price'       => 15.00,
                'weight'              => '1kg',
                'unit'                => 'pack',
                'origin'              => 'New Zealand',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 200,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 40,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 14,
                'thumbnail'           => 'products/green_mussels.jpg',
            ],

            // ─── 6. FISH FILLET ───────────────────────────────────────────────────
            [
                'name'                => 'Premium Dory Fish Fillet (1kg IQF)',
                'slug'                => 'premium-dory-fish-fillet-1kg',
                'category_id'         => $filletCat->id,
                'short_description'   => 'Boneless and skinless white Pangasius Dory fillets with gentle sweet flavor.',
                'description'         => 'Individually Quick Frozen (IQF) boneless, skinless dory fish fillets. 100% net weight with minimal protective glaze. Tender flaky white meat, perfectly suited for fish and chips, lemon butter pan-fry, or Chinese sweet and sour.',
                'sku'                 => 'FILLET-DORY-1KG',
                'retail_price'        => 14.90,
                'walkin_price'        => 13.00,
                'wholesale_price'     => 10.50,
                'trading_price'       => 8.80,
                'weight'              => '1kg',
                'unit'                => 'pack',
                'origin'              => 'Vietnam',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 450,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 50,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 15,
                'thumbnail'           => 'products/barramundi_seabass.jpg',
            ],

            // ─── 7. OTHER FROZEN SEAFOOD ──────────────────────────────────────────
            [
                'name'                => 'Japanese Seasoned Unagi Kabayaki (200g)',
                'slug'                => 'japanese-seasoned-unagi-kabayaki-200g',
                'category_id'         => $otherSeaCat->id,
                'short_description'   => 'Ready-to-heat Japanese grilled eel glazed in sweet savory tare kabayaki sauce.',
                'description'         => 'Prime freshwater eel traditionally charcoal-grilled and coated with rich, glossy unagi tare sauce. Simply defrost and heat in microwave or oven for 3 minutes for restaurant quality unadon eel rice bowls.',
                'sku'                 => 'OTHER-UNAGI-200',
                'retail_price'        => 28.00,
                'walkin_price'        => 25.50,
                'wholesale_price'     => 21.00,
                'trading_price'       => 18.50,
                'weight'              => '200g',
                'unit'                => 'pack',
                'origin'              => 'Japan',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 160,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 40,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 16,
                'thumbnail'           => 'products/loligo_squid.jpg',
            ],

            // ─── 8. STEAMBOAT ─────────────────────────────────────────────────────
            [
                'name'                => 'Steamboat Hotpot Harvest Combo (1kg)',
                'slug'                => 'steamboat-hotpot-harvest-combo-1kg',
                'category_id'         => $steamboatCat->id,
                'short_description'   => 'Premium steamboat platter with seafood tofu cubes, fish balls, and prawn rolls.',
                'description'         => 'An exquisite all-in-one hotpot combo designed for family steamboat feasts and restaurant catering. Packed with artisan golden seafood tofu, cheese fish tofu, bouncy lobster balls, and crispy beancurd rolls. Quick cook in 4 minutes.',
                'sku'                 => 'STEAM-COMBO-1KG',
                'retail_price'        => 26.50,
                'walkin_price'        => 24.00,
                'wholesale_price'     => 19.50,
                'trading_price'       => 17.00,
                'weight'              => '1kg',
                'unit'                => 'pack',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 320,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 50,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 17,
                'thumbnail'           => 'products/steamboat_hotpot_combo.jpg',
            ],

            // ─── 9. MEAT BEEF (MELTIQUE HIGHLIGHT) ────────────────────────────────
            [
                'name'                => 'Meltique Beef Striploin Steak (1kg / 5x200g)',
                'slug'                => 'meltique-beef-striploin-steak-1kg',
                'category_id'         => $meatBeefCat->id,
                'short_description'   => 'Premium Japanese-style Meltique beef striploin with consistent rich marbling.',
                'description'         => 'Mika Gourmet is proud to supply authentic Meltique beef, patented for injecting natural beef fat into prime cuts to achieve exquisite wagyu-like tenderness and marbling. Individual vacuum skin-packed. Melts in the mouth with rich, juicy buttery umami. Certified Halal.',
                'sku'                 => 'BEEF-MELTIQUE-1KG',
                'retail_price'        => 98.00,
                'walkin_price'        => 89.00,
                'wholesale_price'     => 76.00,
                'trading_price'       => 69.00,
                'weight'              => '1kg',
                'unit'                => 'pack',
                'origin'              => 'Australia',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 180,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 5,
                'moq_trading'         => 20,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 18,
                'thumbnail'           => 'products/meltique_beef_steak.jpg',
            ],
            [
                'name'                => 'Frozen Beef Short Ribs Bone-In (1kg)',
                'slug'                => 'frozen-beef-short-ribs-bone-in-1kg',
                'category_id'         => $meatBeefCat->id,
                'short_description'   => 'Center-cut English style beef short ribs, well marbled for slow braising or BBQ.',
                'description'         => 'Meaty bone-in beef short ribs with exceptional intra-muscular fat. Ideal for Korean galbi BBQ, slow-braised red wine beef ribs, or hearty beef soups. Cut to precision thickness.',
                'sku'                 => 'BEEF-RIB-1KG',
                'retail_price'        => 56.00,
                'walkin_price'        => 51.00,
                'wholesale_price'     => 43.00,
                'trading_price'       => 38.50,
                'weight'              => '1kg',
                'unit'                => 'pack',
                'origin'              => 'Australia',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 140,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 6,
                'moq_trading'         => 25,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 19,
                'thumbnail'           => 'products/meltique_beef_steak.jpg',
            ],

            // ─── 10. MEAT LAMB ────────────────────────────────────────────────────
            [
                'name'                => 'Australian Frenched Lamb Cutlets (1kg)',
                'slug'                => 'australian-frenched-lamb-cutlets-1kg',
                'category_id'         => $meatLambCat->id,
                'short_description'   => 'Pasture-fed Australian lamb rack chops, frenched bone for gourmet presentation.',
                'description'         => 'Tender, delicate pasture-raised Australian lamb chops with clean bones (frenched). Naturally mild aroma and juicy succulence. Sear with garlic, rosemary, and olive oil for a 5-star restaurant dining experience.',
                'sku'                 => 'LAMB-FRENCH-1KG',
                'retail_price'        => 82.00,
                'walkin_price'        => 75.00,
                'wholesale_price'     => 64.00,
                'trading_price'       => 58.00,
                'weight'              => '1kg',
                'unit'                => 'pack',
                'origin'              => 'Australia',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 120,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 5,
                'moq_trading'         => 20,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 20,
                'thumbnail'           => 'products/meltique_beef_steak.jpg',
            ],

            // ─── 11. MEAT CHICKEN ─────────────────────────────────────────────────
            [
                'name'                => 'Boneless Chicken Leg & Thigh Fillet (2kg)',
                'slug'                => 'boneless-chicken-leg-thigh-fillet-2kg',
                'category_id'         => $meatChickenCat->id,
                'short_description'   => 'Skin-on boneless chicken thigh cuts, flash-frozen for restaurant prep.',
                'description'         => '100% Halal certified chicken thigh fillets, carefully de-boned while retaining crispy skin. Widely trusted by Japanese eateries for chicken karaage, teriyaki chicken bowls, and charcoal yakitori grills.',
                'sku'                 => 'CHK-THIGH-2KG',
                'retail_price'        => 32.00,
                'walkin_price'        => 29.00,
                'wholesale_price'     => 24.50,
                'trading_price'       => 21.50,
                'weight'              => '2kg',
                'unit'                => 'pack',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 350,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 40,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 21,
                'thumbnail'           => 'products/barramundi_seabass.jpg',
            ],

            // ─── 12. MEAT DUCK ────────────────────────────────────────────────────
            [
                'name'                => 'Gourmet Smoked Duck Breast (200g)',
                'slug'                => 'gourmet-smoked-duck-breast-200g',
                'category_id'         => $meatDuckCat->id,
                'short_description'   => 'Hardwood-smoked tender duck breast fillet with rich aromatic spice cure.',
                'description'         => 'Premium whole duck breast cured and gently smoked over natural hardwood chips. Crispy skin when pan-seared skin-down for 5 minutes, leaving tender rosy meat inside. Halal certified and pre-cooked.',
                'sku'                 => 'DUCK-SMOKED-200',
                'retail_price'        => 13.90,
                'walkin_price'        => 12.50,
                'wholesale_price'     => 9.80,
                'trading_price'       => 8.20,
                'weight'              => '200g',
                'unit'                => 'pack',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 290,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 15,
                'moq_trading'         => 60,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 22,
                'thumbnail'           => 'products/meltique_beef_steak.jpg',
            ],

            // ─── 13. FROZEN PRODUCT FOOD ──────────────────────────────────────────
            [
                'name'                => 'Japanese Premium Crab Sticks / Kanikama (500g)',
                'slug'                => 'japanese-premium-crab-sticks-kanikama-500g',
                'category_id'         => $frozenFoodCat->id,
                'short_description'   => 'High surimi-content Japanese imitation crab meat sticks, silky shred texture.',
                'description'         => 'Premium grade Japanese surimi crab sticks with vivid natural color and fine flaky strands. Excellent for sushi salad, California rolls, steamboat, and fried tempura.',
                'sku'                 => 'PROD-KANIKAMA-500',
                'retail_price'        => 11.50,
                'walkin_price'        => 10.00,
                'wholesale_price'     => 8.20,
                'trading_price'       => 6.90,
                'weight'              => '500g',
                'unit'                => 'pack',
                'origin'              => 'Thailand',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 400,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 20,
                'moq_trading'         => 100,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 23,
                'thumbnail'           => 'products/seafood_tofu_platter.jpg',
            ],

            // ─── 14. DIMSUM ───────────────────────────────────────────────────────
            [
                'name'                => 'Handmade Crystal Shrimp Har Kow (10 pcs)',
                'slug'                => 'handmade-crystal-shrimp-har-kow-10pcs',
                'category_id'         => $dimsumCat->id,
                'short_description'   => 'Translucent wheat starch dumplings filled with crunchy whole sea shrimp.',
                'description'         => 'Traditional Cantonese Dim Sum masterpiece. Crafted with delicate translucent crystal wrappers encasing succulent whole sea shrimp. Steam directly from frozen for 7 minutes for a sparkling, burst-in-your-mouth bite.',
                'sku'                 => 'DIM-HARKOW-10',
                'retail_price'        => 19.80,
                'walkin_price'        => 17.50,
                'wholesale_price'     => 14.00,
                'trading_price'       => 12.00,
                'weight'              => '250g',
                'unit'                => 'pack',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 280,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 12,
                'moq_trading'         => 50,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 24,
                'thumbnail'           => 'products/dimsum_har_kow.jpg',
            ],
            [
                'name'                => 'Traditional Seafood Siew Mai (12 pcs)',
                'slug'                => 'traditional-seafood-siew-mai-12pcs',
                'category_id'         => $dimsumCat->id,
                'short_description'   => 'Handmade dim sum siew mai dumplings filled with prawn, squid and fish.',
                'description'         => 'Authentic Hong Kong dim sum style steamed dumplings with delicate wanton skin, packed with whole prawn pieces and minced fish. Steam for 8 minutes from frozen for a fragrant, juicy breakfast or dim sum feast.',
                'sku'                 => 'DIM-SIEWMAI-12',
                'retail_price'        => 18.00,
                'walkin_price'        => 16.00,
                'wholesale_price'     => 13.00,
                'trading_price'       => 11.00,
                'weight'              => '360g',
                'unit'                => 'pack',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 180,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 50,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 25,
                'thumbnail'           => 'products/seafood_siew_mai.jpg',
            ],

            // ─── 15. READY TO EAT ─────────────────────────────────────────────────
            [
                'name'                => 'Japanese Chuka Wakame Seasoned Seaweed (1kg)',
                'slug'                => 'japanese-chuka-wakame-seasoned-seaweed-1kg',
                'category_id'         => $readyEatCat->id,
                'short_description'   => 'Crunchy shredded seaweed tossed with sesame oil, chili flakes, and toasted sesame.',
                'description'         => 'Classic Japanese izakaya seaweed salad. Crisp, vibrant green and bursting with sweet, nutty sesame flavor. Ready to serve immediately upon thawing. Ideal side dish or appetizer for sushi bars.',
                'sku'                 => 'RTE-WAKAME-1KG',
                'retail_price'        => 22.00,
                'walkin_price'        => 19.50,
                'wholesale_price'     => 16.00,
                'trading_price'       => 13.80,
                'weight'              => '1kg',
                'unit'                => 'pack',
                'origin'              => 'Japan',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 220,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 10,
                'moq_trading'         => 40,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 26,
                'thumbnail'           => 'products/seafood_tofu_platter.jpg',
            ],

            // ─── 16. SNACK FOOD ───────────────────────────────────────────────────
            [
                'name'                => 'Crispy Seafood Spring Rolls (20 pcs / 500g)',
                'slug'                => 'crispy-seafood-spring-rolls-500g',
                'category_id'         => $snackCat->id,
                'short_description'   => 'Golden paper-thin pastry wrapped around seasoned minced shrimp and water chestnuts.',
                'description'         => 'Crisp, golden finger food favorite! Deep fry or air-fry straight from frozen for 6 minutes. Shorter cooking time with intense crackling crunch. Served in hotel banquet receptions and family parties.',
                'sku'                 => 'SNACK-ROLLS-500',
                'retail_price'        => 15.50,
                'walkin_price'        => 13.80,
                'wholesale_price'     => 11.00,
                'trading_price'       => 9.20,
                'weight'              => '500g',
                'unit'                => 'pack',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 310,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 15,
                'moq_trading'         => 60,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 27,
                'thumbnail'           => 'products/seafood_tofu_platter.jpg',
            ],

            // ─── 17. DESSERT ──────────────────────────────────────────────────────
            [
                'name'                => 'Artisan Japanese Matcha & Mango Ice Mochi (6 pcs)',
                'slug'                => 'artisan-japanese-matcha-mango-ice-mochi-6pcs',
                'category_id'         => $dessertCat->id,
                'short_description'   => 'Chewy soft rice flour skin filled with creamy Kyoto matcha & tropical mango gelato.',
                'description'         => 'Delightful frozen Japanese mochi confections crafted with pounded glutinous rice dough wrapped around premium Italian gelato ice cream centers. Keep frozen at -18°C, thaw for 2 minutes before enjoying a cloud-soft bite.',
                'sku'                 => 'DES-MOCHI-6',
                'retail_price'        => 16.50,
                'walkin_price'        => 14.80,
                'wholesale_price'     => 12.00,
                'trading_price'       => 10.00,
                'weight'              => '180g',
                'unit'                => 'box',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'Mika Gourmet',
                'stock_quantity'      => 190,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 12,
                'moq_trading'         => 48,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => false,
                'is_rfq_only'         => false,
                'sort_order'          => 28,
                'thumbnail'           => 'products/dimsum_har_kow.jpg',
            ],

            // ─── 18. SEAFOOD PRODUCTS (SPECIALTY) ─────────────────────────────────
            [
                'name'                => 'Handcrafted Fresh Prawn Paste (200g Tube)',
                'slug'                => 'handcrafted-fresh-prawn-paste-200g',
                'category_id'         => $prodCat->id,
                'short_description'   => '95% pure prawn meat paste in squeeze tube for steamboat hotpot dining.',
                'description'         => 'Made from fresh minced sea prawns with no flour fillers. Springy, succulent texture that puffs up in hot soup broth. Simply squeeze spoonfuls directly into boiling hotpot broth.',
                'sku'                 => 'PROD-PRAWNPASTE-200',
                'retail_price'        => 16.90,
                'walkin_price'        => 15.00,
                'wholesale_price'     => 12.50,
                'trading_price'       => 10.50,
                'weight'              => '200g',
                'unit'                => 'tube',
                'origin'              => 'Malaysia',
                'storage_temp'        => '-18°C',
                'brand'               => 'MST IMPORT AND EXPORT SDN BHD',
                'stock_quantity'      => 260,
                'track_stock'         => true,
                'moq'                 => 1,
                'moq_wholesale'       => 15,
                'moq_trading'         => 60,
                'is_active'           => true,
                'is_walkin_available' => true,
                'is_featured'         => true,
                'is_rfq_only'         => false,
                'sort_order'          => 29,
                'thumbnail'           => 'products/prawn_paste_tube.jpg',
            ],
        ];

        // Clean up dummy "Test" product if present
        Product::withTrashed()->where('name', 'Test')->orWhere('slug', 'test')->forceDelete();

        foreach ($products as $data) {
            $existing = Product::withTrashed()
                ->where('sku', $data['sku'])
                ->orWhere('slug', $data['slug'])
                ->first();

            if ($existing) {
                $existing->update($data);
                if ($existing->trashed()) {
                    $existing->restore();
                }
            } else {
                Product::create($data);
            }
        }

        // Set featured flags on key categories
        Category::whereIn('slug', [
            'fish', 'prawns-shrimps', 'squid', 'crab', 'shellfish', 
            'meat-beef', 'fish-fillet', 'steamboat', 'dimsum', 'seafood-products'
        ])->update(['is_featured' => true]);
    }
}
